version: '3'

services:
  runtests:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/code
      - /code/bin/
      - /code/obj/
    command:
      - /bin/bash
      - /code/run-tests.sh